--"Local" Parameters---------------------------------------------------------------------------------------------------------
SELECT KEY
	,pr.VALUE
	,DESCRIPTION
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS pr
WHERE ID_BOT IN (43)
	--AND KEY LIKE '%CONTROL_TABLE_NAME%'
ORDER BY KEY ASC;
--CONTROL TABLE---------------------------------------------------------------------------------------------------------
SELECT *
FROM RPA.[control_table]
ORDER BY ID DESC;
--GERENCIADOR EXECUCOES---------------------------------------------------------------------------------------------------------
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 43
ORDER BY ID_EXECUTION DESC;

--Tempo EXECUCAO------------------------------------
SELECT 
    ID_BOT
    ,TO_TIMESTAMP(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
    		TO_TIMESTAMP(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') AS DURACAO_INTERVALO
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 43
	AND END_EXECUTION IS NOT NULL
ORDER BY ID_EXECUTION DESC;
--Tempo MEDIO EXECUCAO------------------------------------
SELECT 
    ID_BOT,
    AVG(
        (TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
         TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')) * 1440
    ) AS MEDIA_MINUTOS_DOUBLE
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (43)
GROUP BY ID_BOT
ORDER BY MEDIA_MINUTOS_DOUBLE ASC;

SELECT VALUE FROM REGS.CUSTOMER
WHERE KEY IN ('ExposedPerson') AND "IDENTITY" = '00000045700' AND ROWNUM = 1
ORDER BY CREATIONDATE DESC;

--Active Customer
SELECT STATUS FROM REGS.CUSTOMER_USERS
WHERE CUSTOMERID = 00000045700;

--Cad Pending
SELECT *
FROM REGS.CUSTOMER_PENDENCIES
WHERE CUSTOMERID = '00000045700';

SELECT COUNT(*) AS CAD_PENDING -- 1 CAD FINALIZADO / 0 CAD PENDENTE OU IRREGULAR
FROM REGS.CUSTOMER_PENDENCIES
WHERE STATUSID = 2
	AND PENDENCYTYPE = 1
	AND CUSTOMERID = '00000045700';