SELECT ----------------------------------------------------------------------------------"Local" Parameters
	KEY
	,pr.VALUE
	,DESCRIPTION
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS pr
WHERE ID_BOT IN (85)
ORDER BY KEY ASC;

SELECT  ----------------------------------------------------------------------------------Check exec status
 *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 85
ORDER BY ID_EXECUTION DESC;

---------------------------------------------------------------------------------- CONTROL TABLE
SELECT *
FROM RPA.[control_table]
ORDER BY ID DESC;
---------------------------------------------------------------------------------- 
SELECT 
       CD_CLIENT, 
       IDENTITY,
       PROCESS_ID,
       ROUND(VALUE_ORDER,2) AS VALUE_ORDER,
       ROUND(VALUE_BLOCKED,2) AS VALUE_BLOCKED,
       ROUND(VALUE_ORDER - VALUE_BLOCKED,2) AS VALUE_RESTBLOCK,
       MONITORING_START,
       MONITORING_DEADLINE, 
       CASE WHEN VALUE_ORDER = VALUE_BLOCKED OR MONITORING_DEADLINE < SYSDATE THEN 'NAO' ELSE 'SIM' END AS MONITORING
FROM RPA.RPA_CTRL_OFICIOS_MONITORADOS
ORDER BY MONITORING_START DESC;

--Queries estão NO bucket
SELECT 
   CD_CLIENT, 
   IDENTITY,
   PROCESS_ID,
   ROUND(VALUE_ORDER,2) AS VALUE_ORDER,
   ROUND(VALUE_BLOCKED,2) AS VALUE_BLOCKED,
   ROUND(VALUE_ORDER - VALUE_BLOCKED,2) AS VALUE_RESTBLOCK,
   MONITORING_START,
   MONITORING_DEADLINE, 
   CASE WHEN VALUE_ORDER = VALUE_BLOCKED OR MONITORING_DEADLINE < SYSDATE THEN 'NAO' ELSE 'SIM' END AS MONITORING
FROM RPA.RPA_CTRL_OFICIOS_MONITORADOS
WHERE CD_CLIENT = '12071591'


SELECT 
   *
FROM RPA.RPA_CTRL_OFICIOS_MONITORADOS
ORDER BY ID DESC;