--"Local" Parameters---------------------------------------------------------------------------------------------------------
SELECT 
	KEY
	,pr.VALUE
	,DESCRIPTION
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS pr
WHERE ID_BOT IN (93)
ORDER BY KEY ASC;
--Check exec status---------------------------------------------------------------------------------------------------------
SELECT 
	*
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 93
	AND STATUS = 2
ORDER BY ID_EXECUTION DESC;
--CONTROL TABLE---------------------------------------------------------------------------------------------------------
SELECT
	*
FROM
	RPA.RPA_CTRL_SINCAD_ERRORS
WHERE
	STATUS = 3
ORDER BY
	1 DESC;
--Global bot Parameters---------------------------------------------------------------------------------------------------------
SELECT * 
FROM RPA.RPA_GERENCIADOR_GLOBAL_PARAMETERS
ORDER BY key asc;
--------------------------------------------------------------------------------------------------------------------------------
SELECT
*
FROM (
SELECT
CLIGER.CD_CPFCGC AS Documento,
TSCDXCON.NUM_IDT_CON AS Conta,
LOTE.DTHR_GER_LOTE_MSG AS DataEnvio,
ERRO_ICADX.COD_IDT_REGR AS CodErro,
ERRO_ELEM.DESC_ERRO AS Campo,
ERRO_ICADX.DESC_REGR AS Descricao,
REPLACE(ERRO_ELEM.TXT_CNTD_ELEM, '''', '') AS Conteudo,
ENVIO.COD_SITU_ENVIO AS TipoErro,
RANK () OVER (PARTITION BY TSCDXCON.NUM_IDT_CON ORDER BY LOTE.DTHR_GER_LOTE_MSG DESC ) AS "RANK"
FROM
CORRWIN.TSCDXMSG_LOTE LOTE
LEFT JOIN CORRWIN.TSCDXMSG_ICADX ICADX ON
( LOTE.DTHR_GER_LOTE_MSG = ICADX.DTHR_GER_LOTE_MSG
AND LOTE.NUM_SEQ_LOTE = ICADX.NUM_SEQ_LOTE )
LEFT JOIN CORRWIN.TSCDXSITU_ENVIO ENVIO ON
(ICADX.COD_SITU_ENVIO = ENVIO.COD_SITU_ENVIO)
LEFT JOIN CORRWIN.TSCDXMSG_ERRO_ICADX ERRO_ICADX ON
( ICADX.COD_SEQ_MSG_ICADX = ERRO_ICADX.COD_SEQ_MSG_ICADX )
LEFT JOIN CORRWIN.TSCDXMSG_ERRO_ELEM ERRO_ELEM ON
( ERRO_ICADX.COD_SEQ_MSG_ICADX = ERRO_ELEM.COD_SEQ_MSG_ICADX )
LEFT JOIN CORRWIN.TSCDXMSG_ICADX_CAD ICADX_CAD ON
( ICADX.COD_SEQ_MSG_ICADX = ICADX_CAD.COD_SEQ_MSG_ICADX )
LEFT JOIN CORRWIN.TSCDXCON TSCDXCON ON
(ICADX_CAD.NUM_SEQ_CAD = TSCDXCON.NUM_SEQ_CON)
LEFT JOIN CORRWIN.TSCDXCLI_CLIGER CLIGER ON
( TSCDXCON.NUM_SEQ_CLIENTE = CLIGER.NUM_SEQ_CLIENTE )
WHERE
ICADX_CAD.NUM_TAB_SCDX = 10
AND TRUNC(LOTE.DTHR_ARQ_ENV) >= TRUNC(SYSDATE - %DAYSTOSUBTRACT%)
AND ENVIO.COD_SITU_ENVIO = 'ERR')
LEFT JOIN (select P.Customerid from regs.customer_pendencies p
WHERE P.PENDENCYTYPE = 7
AND p.STATUSID = 1 ) PENDENCIAS ON Documento = PENDENCIAS.Customerid
WHERE "RANK" = 1
AND PENDENCIAS.Customerid IS NULL