SELECT ----------------------------------------------------------------------------------"Local" Parameters
	KEY
	,pr.VALUE
	,DESCRIPTION 
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS pr
WHERE ID_BOT IN (146)
	AND VALUE LIKE '%CPF%'
ORDER BY KEY ASC;

SELECT  ----------------------------------------------------------------------------------Check exec status
	ID_EXECUTION 
	,COUNT_EXEC 
	,HOST_NAME 
	,EXTERNAL_ID
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 146
ORDER BY ID_EXECUTION DESC;
---------------------------------------------------------------------------------- CONTROL TABLE
SELECT * FROM RPA.RPA_CTRL_REGSOL_KYC_CUSTOMER_DATA_EXTRACTION
WHERE STATUS IN (
	'CANCELED'
	,'Erro inesperado ao coletar customer id'
)

SELECT
	*
FROM
	RPA.RPA_CTRL_REGSOL_KYC_CUSTOMER_DATA_EXTRACTION
WHERE CPF = '00000045800';

SELECT * 
FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST 
WHERE CUSTOMERID = '00000000100'
ORDER BY ID DESC;

SELECT * FROM RPA.RPA_CTRL_REGSOL_KYC_CUSTOMER_DATA_EXTRACTION 
WHERE CPF = '00000000100'

SELECT * 
FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST

	SELECT * 
	FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST 
	WHERE RULE_DATE = '202602'
	ORDER BY ID DESC;

SELECT 
    A.CUSTOMERID,
    QTY_ALERTS,
    MAX(B.PREVIOUS_MONTH_ALERT) AS PREVIOUS_MONTH_ALERT
FROM (
SELECT 
CUSTOMERID,
SUM(QTY_ALERTS) AS QTY_ALERTS
FROM (
SELECT 
        CUSTOMERID,
        CASE WHEN RULE_DATE = TO_CHAR(add_months(sysdate, - 1),'YYYYMM')  THEN 0 --Atribuir 0 Caso tenha alerta para o mes de referencia ANO ATUAL MES-1. 
             ELSE SUM(REC_AML_OPS)
        END AS QTY_ALERTS
    FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST
    WHERE TO_DATE(RULE_DATE, 'YYYYMM') >= add_months(sysdate, -6) --Busca resultados somente dos ultimos 6 meses
    GROUP BY CUSTOMERID, RULE_DATE)
    GROUP BY CUSTOMERID
) A
LEFT JOIN (
    SELECT
        CUSTOMERID, 
        CASE WHEN RULE_DATE = TO_CHAR(add_months(sysdate, - 2),'YYYYMM') THEN 'Sim' --Valida se teve alerta NO mes anterior. ANO ATUAL MES de referencia é sempre anterior, entao faz o calculo com -2.
             ELSE 'Não'
        END AS PREVIOUS_MONTH_ALERT
    FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST
) B ON A.CUSTOMERID = B.CUSTOMERID
WHERE A.CUSTOMERID = '00000045900'
GROUP BY A.CUSTOMERID, QTY_ALERTS;

SELECT
    A.CUSTOMERID,
    QTY_ALERTS,
    MAX(B.PREVIOUS_MONTH_ALERT) AS PREVIOUS_MONTH_ALERT
FROM
    (
    SELECT
        CUSTOMERID,
        SUM(QTY_ALERTS) AS QTY_ALERTS
    FROM
        (
        SELECT
            CUSTOMERID,
            CASE
                WHEN RULE_DATE = TO_CHAR(add_months(sysdate, - 1), 'YYYYMM') THEN 0
                ELSE SUM(REC_AML_OPS) 
            END AS QTY_ALERTS 
        FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST 
        WHERE RULE_DATE <> '202600' -- Ignora o valor inválido explicitamente
          AND RULE_DATE >= TO_CHAR(add_months(sysdate, -6), 'YYYYMM') -- Filtra como string (mais rápido e seguro)
        GROUP BY CUSTOMERID, RULE_DATE
        ) 
    GROUP BY CUSTOMERID 
    ) A 
LEFT JOIN ( 
    SELECT 
        CUSTOMERID, 
        CASE 
            WHEN RULE_DATE = TO_CHAR(add_months(sysdate, - 2),'YYYYMM') THEN 'Sim' 
            ELSE 'Não' 
        END AS PREVIOUS_MONTH_ALERT 
    FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST 
    WHERE RULE_DATE <> '202600' -- Garante consistência no Join também
) B ON A.CUSTOMERID = B.CUSTOMERID 
WHERE A.CUSTOMERID = '00000045900' 
GROUP BY A.CUSTOMERID, QTY_ALERTS;

SELECT * FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST

SELECT RULE_DATE , COUNT(*) FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST
GROUP BY RULE_DATE
ORDER BY RULE_DATE;

SELECT CUSTOMERID, LISTAGG(RULE_DATE, ', ') WITHIN GROUP (ORDER BY RULE_DATE) AS List
FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST
WHERE CUSTOMERID = '00000045900'
GROUP BY CUSTOMERID;

SELECT * DELETE FROM RPA.RPA_AML_KYC_ALERTS_RECURRENCE_NUINVEST
WHERE RULE_DATE = '202600';


