SELECT ---------------------------------------------------------------------------------- "Local" Parameters
	KEY
	,pr.VALUE
	,DESCRIPTION
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS pr
WHERE ID_BOT IN (201)
ORDER BY KEY ASC;

SELECT  ---------------------------------------------------------------------------------- Check exec status
 *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 201
ORDER BY ID_EXECUTION DESC;
---------------------------------------------------------------------------------- CONTROL TABLE
SELECT *
FROM RPA.RPA_CTRL_OMB_V2_RECEBIMENTO_DOS_CASOS_PROCON_STEP2
WHERE TRUNC(DT_START_EXECUTION) = TRUNC(SYSDATE)
ORDER BY ID DESC;

SELECT * FROM RPA.RPA_CTRL_OMB_V2_RECEBIMENTO_DOS_CASOS_PROCON_STEP2
WHERE ID = 6387;

SELECT ID
	,PROTOCOL_NUMBER
	,DOCUMENT_TYPE 
	,STATUS 
	,FINE_DOCUMENT 
	,PERFORM_ZENDESK_STEP
	,PERFORM_ELAW_STEP
	,DOCUMENT_DUPLICATE
	,MOVE_FILE_REGISTRATION_OK
	,SEND_SLACK_MESSAGE
	,REGISTER_IN_SPREADSHEET
	,TYPE_ZENDESK_CLIENT
	,TYPE_ZENDESK_REGULATOR
	,SAVE_FILE_ELAW
	,ID_EXECUTION
FROM RPA.RPA_CTRL_OMB_V2_RECEBIMENTO_DOS_CASOS_PROCON_STEP2
WHERE TRUNC(DT_EXEC) = TRUNC(SYSDATE)
ORDER BY ID DESC;
959726

SELECT * 
FROM RPA.RPA_CTRL_OMB_V2_RECEBIMENTO_DOS_CASOS_PROCON_STEP2
WHERE TRUNC(DT_EXEC) = TRUNC(SYSDATE-3);
---------------------------------------------------------------------------------- Global bot Parameters
SELECT * 
FROM RPA.RPA_GERENCIADOR_GLOBAL_PARAMETERS
ORDER BY KEY DESC;
----------------------------------------------------------------------------------

SELECT ID 
	,PROTOCOL_NUMBER
	,DOCUMENT_TYPE 
	,STATUS
	,OBSERVATION
FROM RPA.RPA_CTRL_OMB_V2_RECEBIMENTO_DOS_CASOS_PROCON_STEP2
WHERE ID = 5539
ORDER BY ID DESC;