SELECT ----------------------------------------------------------------------------------"Local" Parameters
	KEY
	,pr.VALUE
	,DESCRIPTION 
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS pr
WHERE ID_BOT IN (219)
ORDER BY KEY ASC;

SELECT  ----------------------------------------------------------------------------------Check exec status
 *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 219
ORDER BY ID_EXECUTION DESC;
---------------------------------------------------------------------------------- CONTROL TABLE
SELECT *
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
ORDER BY ID DESC;

SELECT *
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE OBS_STATUS = 'NEW'
ORDER BY GDRIVE_FILE_NAME DESC;


---------------------------------------------------------------------------------- 
--PATH dos prompts: https://drive.google.com/drive/folders/1vR_JoZ_KwsJROO1j3cQHAWpY8vhlsaob


SELECT
	*
FROM
	RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE ID IN (6135)
ORDER BY ID DESC;

SELECT
	IA_DOCUMENT_TYPE 
FROM
	RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
GROUP BY IA_DOCUMENT_TYPE 

SELECT ID FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF_IA_COLLECTED_PAGES
WHERE TRUNC(DT_UPDATE) = TRUNC(SYSDATE)
GROUP BY ID;

	STATUS = 3
ORDER BY
	ID DESC

SELECT ID
	,STATUS
	,GDRIVE_FILE_LINK
	,IA_DOCUMENT_TYPE
	,OBS_STATUS
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE OBS_STATUS LIKE 'Nao foi possivel identificar o tipo do documento%'
ORDER BY ID DESC

SELECT 
	*
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE ID = 2041

SELECT 
	IA_DOCUMENT_TYPE
	,OBS_STATUS
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE OBS_STATUS LIKE 'Can not assign%'
group BY
	IA_DOCUMENT_TYPE
	,OBS_STATUS

SELECT ID
	,STATUS
	,GDRIVE_FILE_LINK
	,IA_DOCUMENT_TYPE
	,OBS_STATUS
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE ID IN (1774, 1778, 1783, 1792, 2041)
ORDER BY ID DESC


SELECT *
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE ID IN (1807)
ORDER BY ID DESC

SELECT ID
	,STATUS
	,GDRIVE_FILE_LINK
	,IA_DOCUMENT_TYPE
	,OBS_STATUS
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE ID IN (1778, 1783)
ORDER BY ID DESC

SELECT *
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE IA_DOCUMENT_TYPE = 'Relatório de movimentações'
ORDER BY ID DESC

SELECT ID
	,STATUS
	,GDRIVE_FILE_LINK
	,IA_DOCUMENT_TYPE
	,OBS_STATUS
FROM RPA.RPA_CTRL_APLICACAO_DE_OCR_EM_EDD_PF
WHERE IA_DOCUMENT_TYPE = 'Declaração de Rendimentos'
ORDER BY ID DESC

Can not assign CDbl(jResponseAI("value").ToString()) to dTotalValue.

{
  "IR": "1PguvL2abe7CYTwMcuIwwokipfdM748L88JKgiNQZNjc", ok
  "DECORE": "1JHsg8uUzlfKoLNPhOZMFeex0wfSv7cZnLw28juli-sM", ok
  "HOLERITE": "1rFAOHiYQmMmnY3RT4L_-_mdAyGNpSmIZZSd_H1TURwQ", ok
  "PROLABORE": "17HAI2uglQkMKG-cHwj-_OYsUqDT59WvwdNbHfbJ1Xl4", tem o exemplo
  "EXTRATO_BANCARIO": "1ggEq007MPb7Kvm6Ujpy4Am774hNwUNuDtj85kppORUs",
  "RELATORIO_VENDAS": "1n500Me-aeUhB56SG0N07Q0Fk-khosWIeABYpkUzPcBU", ok
  "INSS": "1oul6k8FTFxbL3Zb-esabZISDfiCyiWGi81bbKyKyWds", tem o exemplo 
  "APOSENTADORIA": "10OWO13QLVQ26jOaTogfpO_lVDtSRXdTbR2I6_I2uNJQ" tem o exemplo 
}