--GERENCIADOR EXECUCOES---------------------------------------------------------------------------------------------------------
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 85 
ORDER BY ID_EXECUTION DESC;

SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
	)
ORDER BY ID_EXECUTION DESC;

SELECT id_bot
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
	)
	AND ID_EXECUTION BETWEEN 1092769 AND 1092806
ORDER BY ID_EXECUTION DESC;
--validar se os bots utilizam custody: 167, 93, 192

SELECT 
	*
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 180
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/yyyy') = TO_CHAR(SYSDATE, 'MM/yyyy'))
ORDER BY ID_EXECUTION DESC;
--CRASHES--------------------------------------------------------------------------------------------------
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE STATUS = 2
ORDER BY ID_EXECUTION DESC;

--Bots de Ops
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
WHERE BU = 'Brazil - Operations'
	AND ID = 
ORDER BY ID ASC;


--CRASHES DE OPS
SELECT
	*
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ENVIRONMENT = '3'
	AND STATUS NOT IN (2, 6)
	AND ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
	)
ORDER BY ID_EXECUTION DESC;

SELECT --VIEW
	ge.ID_EXECUTION
	,ge.INI_EXECUTION 
	,ge.END_EXECUTION 
	,ge.ID_BOT 
	,ge.STATUS 
	,ge.DESCR_ERR
	,ge.HOST_NAME 
	,ge.PROCESS_NAME 
	,ge.CURRENT_USER 
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES ge
INNER JOIN RPA.RPA_AA_GERENCIADOR_ROBOS gr
	ON ge.ID_BOT = gr.ID
WHERE ENVIRONMENT = 3
	AND ge.STATUS IN (2, 6)
	AND gr.BU = 'Brazil - Operations'
	AND ge.ID_EXECUTION  > 1096289
ORDER BY ID_EXECUTION DESC; 
------------------------------------------------------------------------------------------------------HUX
SELECT TABLE_NAME, OP
FROM RPA.RPA_AA_TABLES_PERMITIDAS;

SELECT ID
	,BU
FROM RPA.RPA_AA_GERENCIADOR_ROBOS
ORDER BY ID ASC; 

SELECT ID
	,BU
FROM RPA.RPA_AA_GERENCIADOR_ROBOS
WHERE ENABLE  = 182
ORDER BY ID ASC; 

SELECT DISTINCT BU 
FROM RPA.RPA_AA_GERENCIADOR_ROBOS

-- Verifica quais bots precisam inserir o EXTERNAL ID (6.1.9 da lib Nubank) considerando o mes presente e o mes anterior
SELECT DISTINCT ID_BOT
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
			AND gr.ENABLE = '1')
	AND EXTERNAL_ID IS NULL
	AND ID_BOT NOT IN (SELECT ID_BOT
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
			AND gr.ENABLE = '1')
	AND EXTERNAL_ID IS NOT NULL
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/yyyy') = TO_CHAR(SYSDATE, 'MM/yyyy'))
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/yyyy') = TO_CHAR(SYSDATE, 'MM/yyyy')
ORDER BY ID_BOT ASC;




--TEMPO SEM CRASH
SELECT ID_BOT
	,TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')
	,ROUND((SYSDATE - TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')) * 24, 2) AS HORAS_SEM_CRASHES
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations')
	AND STATUS = 2
ORDER BY ID_EXECUTION DESC;

SELECT ROUND((TO_DATE('07/05/2026 20:48:52', 'DD/MM/YYYY HH24:MI:SS') - TO_DATE('05/05/2026 16:34:09', 'DD/MM/YYYY HH24:MI:SS')) * 24, 2) AS HORAS_SEM_CRASHES
FROM DUAL;
--Tempo EXECUCAO------------------------------------
SELECT 
    ID_BOT
    ,INI_EXECUTION
    ,TO_TIMESTAMP(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
    		TO_TIMESTAMP(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') AS DURACAO_INTERVALO
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 226
	--AND END_EXECUTION IS NOT NULL
ORDER BY ID_EXECUTION DESC;
--Tempo MEDIO EXECUCAO------------------------------------
SELECT 
    ID_BOT,
    ROUND(
    	AVG(
	        (TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
	         TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')) * 24
    	)
	, 2) AS TEMPO_EXEC_HORA_DOUBLE
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 48
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/YYYY') = '05/2026'
GROUP BY ID_BOT;