SELECT execs.ID_BOT 
	,execs.INI_EXECUTION 
	,execs.STATUS 
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES execs
WHERE ID_BOT = 21
ORDER BY execs.ID_EXECUTION DESC;

SELECT 
    TO_CHAR(TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM'), 'MM/yyyy') AS PERIOD
  , ID_BOT 
  , COUNT(*) AS QTDE_SUCESSO
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES execs
INNER JOIN RPA.RPA_AA_GERENCIADOR_ROBOS gr
ON gr.ID =  execs.ID_BOT 
WHERE execs.STATUS = 1
	AND gr.BU = 'Brazil - Operations'
	AND INI_EXECUTION IS NOT NULL
GROUP BY 
    ID_BOT
  , TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM')
ORDER BY 
	ID_BOT ASC
    , TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM') ASC;

SELECT --Qtde de erros por bot/periodo dos bots que eu tive mais atuacao
    TO_CHAR(TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM'), 'MM/yyyy') AS PERIOD
  , ID_BOT 
  , COUNT(*) AS QTDE_EXECS
  , COUNT(CASE WHEN execs.STATUS = 1 THEN 1 END) AS QTDE_SUCESSO
  , COUNT(CASE WHEN execs.STATUS NOT IN (1, 5) THEN 1 END) AS QTDE_ERROS
  , COUNT (execs.COUNT_EXEC) AS QTDE_ITENS
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES execs
INNER JOIN RPA.RPA_AA_GERENCIADOR_ROBOS gr
   ON gr.ID = execs.ID_BOT 
WHERE gr.BU = 'Brazil - Operations'
  AND INI_EXECUTION IS NOT NULL
  AND ID_BOT IN (21, 35, 85, 130, 144, 196, 201, 208)
GROUP BY 
    ID_BOT
  , TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM')
ORDER BY 
    ID_BOT ASC
  , TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM') ASC;

------------TEMPO MEDIO DE EXEC
SELECT 
	TO_CHAR(TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM'), 'MM/yyyy') AS PERIOD
	,ID_BOT
	,ROUND(
    	AVG(
	        (TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
	         TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')) * 24
    	)
	, 2) AS TEMPO_EXEC_HORA_DOUBLE
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (130)
GROUP BY ID_BOT
	, TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM')
ORDER BY TRUNC(TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM') ASC;




SELECT * FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
WHERE gr.BU = 'Brazil - Operations'
ORDER BY ID ASC;



SELECT ID
	,BU
FROM RPA.RPA_AA_GERENCIADOR_ROBOS
ORDER BY ID ASC; 

SELECT ID
	,BU
FROM RPA.RPA_AA_GERENCIADOR_ROBOS
WHERE ENABLE  = 182
ORDER BY ID ASC; 

SELECT DISTINCT BU 
FROM RPA.RPA_AA_GERENCIADOR_ROBOS

-- Verifica quais bots precisam inserir o EXTERNAL ID (6.1.9 da lib Nubank) considerando o mes presente e o mes anterior
SELECT DISTINCT ID_BOT
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
			AND gr.ENABLE = '1')
	AND EXTERNAL_ID IS NULL
	AND ID_BOT NOT IN (SELECT ID_BOT
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations'
			AND gr.ENABLE = '1')
	AND EXTERNAL_ID IS NOT NULL
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/yyyy') = TO_CHAR(SYSDATE, 'MM/yyyy'))
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/yyyy') = TO_CHAR(SYSDATE, 'MM/yyyy')
ORDER BY ID_BOT ASC;
--GERENCIADOR EXECUCOES---------------------------------------------------------------------------------------------------------
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 215
ORDER BY ID_EXECUTION DESC;

SELECT 
	*
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 235
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/yyyy') = TO_CHAR(SYSDATE, 'MM/yyyy'))
ORDER BY ID_EXECUTION DESC;
--CRASHES--------------------------------------------------------------------------------------------------
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE STATUS = 2
ORDER BY ID_EXECUTION DESC;

--Bots de Ops
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
WHERE BU = 'Brazil - Operations'
ORDER BY ID ASC;

--crashes de ops
SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ENVIRONMENT = 3
	AND ID_BOT IN (
		SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations')
	AND END_EXECUTION LIKE '%2026 %'
ORDER BY ID_EXECUTION DESC;



--TEMPO SEM CRASH
SELECT ID_BOT
	,TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')
	,ROUND((SYSDATE - TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')) * 24, 2) AS HORAS_SEM_CRASHES
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT IN (SELECT gr.ID 
		FROM RPA.RPA_AA_GERENCIADOR_ROBOS gr
		WHERE BU = 'Brazil - Operations')
	AND STATUS = 2
ORDER BY ID_EXECUTION DESC;

SELECT ROUND((TO_DATE('07/05/2026 20:48:52', 'DD/MM/YYYY HH24:MI:SS') - TO_DATE('05/05/2026 16:34:09', 'DD/MM/YYYY HH24:MI:SS')) * 24, 2) AS HORAS_SEM_CRASHES
FROM DUAL;
--Tempo EXECUCAO------------------------------------
SELECT 
    ID_BOT
    ,INI_EXECUTION
    ,TO_TIMESTAMP(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
    		TO_TIMESTAMP(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') AS DURACAO_INTERVALO
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 226
	--AND END_EXECUTION IS NOT NULL
ORDER BY ID_EXECUTION DESC;
--Tempo MEDIO EXECUCAO------------------------------------
SELECT 
    ID_BOT,
    ROUND(
    	AVG(
	        (TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS') - 
	         TO_DATE(INI_EXECUTION, 'DD/MM/YYYY HH24:MI:SS')) * 24
    	)
	, 2) AS TEMPO_EXEC_HORA_DOUBLE
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_BOT = 48
	AND TO_CHAR(TO_DATE(END_EXECUTION, 'DD/MM/YYYY HH24:MI:SS'), 'MM/YYYY') = '05/2026'
GROUP BY ID_BOT;