SELECT --"Local" Parameters
	ID_BOT 
	,KEY
	,VALUE
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS
WHERE ID_BOT  IN (29)
ORDER BY KEY ASC;

SELECT *
FROM RPA.RPA_AA_CTRL_TRANSF_JUD_SPB
WHERE VARA LIKE '%ª%'
	OR VARA LIKE '%ª%'
ORDER BY ID DESC