SELECT * FROM CORRWIN.TTS_SPB_REC WHERE NUM_CTR_STR = 'STR20260430034398197'  ORDER BY CORRWIN.TTS_SPB_REC.DATA_HOR_BAC DESC

SELECT * 
FROM rpa.RPA_AA_FINOPS_CADASTRO_STR
ORDER BY ID DESC;

SELECT * 
FROM rpa.RPA_AA_FINOPS_CADASTRO_STR
WHERE CPF_CNPJ = 4432828200
ORDER BY ID DESC

SELECT *
FROM RPA.RPA_AA_GERENCIADOR_EXECUCOES
WHERE ID_EXECUTION = 990601
