SELECT
	DISTINCT DESTINATION_BROKER_CODE
FROM
	RPA.RPA_CTRL_PORTABILIDADE rcp
WHERE
	STATUS IN ('EMS PENDENTE', 'EMS ATUALIZADO')
	AND TRUNC(SYSDATE) = TRUNC(UPDATE_DT)
	AND CONVERT( STVM_TYPE, 'US7ASCII') = 'Tesouro Direto'
	AND REASON = 'Processado'