SELECT
	ID ,
	ID_STVM ,
	ID_INTRANET ,
	LENGTH(ID_INTRANET)
FROM
	RPA.RPA_CTRL_PORTABILIDADE
WHERE
	CONVERT( STVM_TYPE, 'US7ASCII') = 'Renda Variavel'
	AND STATUS = 'Em Analise'
	AND LENGTH(ACTIVE_NAME) > 6
	AND NOT REGEXP_LIKE(ACTIVE_NAME, '[[:alpha:]]$')

SELECT 
	*
FROM
	RPA.RPA_CTRL_PORTABILIDADE rcp
WHERE
	rcp.DESTINATION_BROKER_CODE = 1099
	AND STATUS = 'Em Analise'
	AND CONVERT( STVM_TYPE, 'US7ASCII') = 'Renda Variavel';
	