
SELECT 
	NOME_HERDEIRO
	,JIRA_KEY 
	,CTRL_IF
	,RETURN_STATUS

FROM RPA.RPA_CTRL_TRANSF_ESPOLIO
WHERE 
	--CPF_FALECIDO = '00000046800'
	--JIRA_KEY = 'SPL-2122'
	--RETURN_STATUS <> 'Efetivado' AND RETURN_STATUS <> 'Devolvido' AND RETURN_STATUS <> 'Mensagem Rejeitada'
ORDER BY ID DESC;

SELECT 
	/*NOME_HERDEIRO AS "Nome"
	,JIRA_KEY AS "Ticket"
	,CTRL_IF AS "ID"
	,RETURN_STATUS AS "Situacao"*/
*
FROM RPA.RPA_CTRL_TRANSF_ESPOLIO
WHERE 
	--CPF_FALECIDO = '00000046800'
	JIRA_KEY = 'SPL-2071' OR JIRA_KEY ='SPL-2087'
ORDER BY ID DESC;

SELECT * FROM RPA.RPA_CTRL_TRANSF_ESPOLIO 
WHERE STATUS = 'APPROVAL REQUESTED';

  
SELECT * FROM RPA.RPA_CTRL_TRANSF_ESPOLIO
WHERE
	STATUS = 'CANHAO DONE'
	AND ISPB_HERDEIRO <> '62169875';