SELECT ------------------------------------------------------------"Local" Parameters
	ID_BOT 
	,KEY
	,VALUE
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS
WHERE ID_BOT  IN (149)
ORDER BY KEY ASC;
------------------------------------------------------------------------------------------

SELECT * FROM RPA.RPA_CTRL_PO_NOTIFICATION WHERE TRUNC(DT_EXEC) = TRUNC(SYSDATE)  	AND STATUS <> 'SEND_NOTIFICATION' ORDER BY ID DESC

SELECT * FROM RPA.RPA_CTRL_PO_NOTIFICATION WHERE TRUNC(DT_EXEC) = TRUNC(SYSDATE)  	AND STATUS = 'NOTIFICATION_SENT' ORDER BY ID DESC

SELECT * FROM RPA.RPA_CTRL_PO_NOTIFICATION
WHERE TRUNC(DT_EXEC) = TRUNC(SYSDATE) 
	AND STATUS = 'EMAIL_ADDRESS_NOT_FOUND';

SELECT STATUS FROM RPA.RPA_CTRL_PO_NOTIFICATION
GROUP BY STATUS;

SELECT
	STATUS
FROM
	RPA.RPA_CTRL_PO_NOTIFICATION
WHERE
	TRUNC(DT_EXEC) = TRUNC(SYSDATE)
	AND STATUS <> 'SEND_NOTIFICATION'
GROUP BY STATUS
