SELECT --"Local" Parameters
	ID_BOT 
	,KEY
	,VALUE
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS
WHERE ID_BOT  IN (197)
ORDER BY KEY ASC;

SELECT
	OPENING_ID ,
	TO_CHAR(UPDATE_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF3') AS data_formatada
FROM
	RPA.RPA_CTRL_PC_INTEGRATION_GH_ORACLE
WHERE
	STATUS IS NOT NULL
	
	SELECT
	OPENING_ID ,
	TO_CHAR(UPDATE_AT, 'YYYY-MM-DD"T"HH24:MI:SS.FF3') AS data_formatada
FROM
	RPA.RPA_CTRL_PC_INTEGRATION_GH_ORACLE
WHERE
	STATUS IS NOT NULL
	ORDER BY UPDATE_AT DESC
