SELECT --"Local" Parameters
	ID_BOT 
	,KEY
	,VALUE
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS
WHERE ID_BOT  IN (193)
ORDER BY KEY desc;

SELECT 
*
FROM RPA.RPA_CTRL_TED_OUT_NUINVEST
INSERT INTO RPA.RPA_CTRL_TED_OUT_NUINVEST (
DT_EXEC,
CPF,
ACCOUNTNUMBER,
BOLETA,
BANK,
AGENCIA,
ACCOUNT_CC,
TELEPHONE_EMS,
ALTER_CAD,
STATUS,
REASON,
TP_ACCOUNT,
DT_REQUEST
) VALUES (
SYSDATE,
'%CPF%',
'%ACCOUNTNUMBER%',
'%BOLETA%',
'%BANK%',
'%AGENCIA%',
'%ACCOUNT_CC%',
'%TELEPHONE_EMS%',
'%ALTER_CAD%',
'%STATUS%',
'%REASON%',
'%TP_ACCOUNT%',
TO_DATE('%DT_REQUEST%', 'MM/DD/YYYY HH24:MI:SS')
)
INSERT INTO CORRWIN.TTSINTOUCL (
    DT_MOVIMENTO,
    DT_REFERENCIA,
    TP_MOVIMENTO,
    IN_LIQUIDANTE,
    CD_CLIENTE,
    VL_LANCAMENTO,
    CD_GRUCOM_LIQ,
    CD_BANCO,
    CD_AGENCIA,
    NR_CONTA,
    CD_BANCO_CLI,
    CD_AGENCIA_CLI,
    DV_AGENCIA_CLI,
    NR_CONTA_CLI,
    DV_CONTA_CLI,
    TP_CONTA_CLI,
    IN_INTEGRADO,
    CD_SIST_EXT
) VALUES (
    TO_DATE(SYSDATE, 'DD/MM/RRRR'),
    TO_DATE(SYSDATE, 'DD/MM/RRRR'),
    'C',
    'N',
    %CD_CLIENTE%,
    %VL_LANCAMENTO%,
    17,
    '140',
    '0001',
    712,
    '%CD_BANCO_CLI%',
    '%CD_AGENCIA_CLI%',
    '%DV_AGENCIA_CLI%',
    '%NR_CONTA_CLI%',
    '%DV_CONTA_CLI%',
    '%TP_CONTA_CLI%',
    'N',
    'EASYRESG'
)
