SELECT --"Local" Parameters
	ID_BOT 
	,KEY
	,VALUE
FROM RPA.RPA_AA_GERENCIADOR_PARAMETERS
WHERE ID_BOT  IN (220)
ORDER BY KEY ASC;

SELECT
	*
FROM
	RPA.RPA_CTRL_SOX_OPS_GRANT_REVOKING
WHERE TO_DATE(DT_INSERT) = TO_DATE(SYSDATE)
ORDER BY
	ID DESC;

SELECT
	*
FROM
	RPA.RPA_CTRL_SOX_OPS_GRANT_REVOKING
WHERE
	( STATUS = '3'
		AND APP IN ('nettrader', 'Net Trader - NuInvest')
			AND TICKET_TYPE = 'Remove' )
	OR ( STATUS = '1'
		AND OBS_STATUS = 'Pre Cadastro Sucesso'
		AND TICKET_TYPE = 'Add'
		AND APP IN ('nettrader', 'Net Trader - NuInvest'));



SELECT * FROM RPA.RPA_CTRL_SOX_OPS_GRANT_REVOKING
WHERE STATUS = '3'
ORDER BY ID DESC;