SELECT * 
FROM RPA.RPA_CTRL_ALERTA_RECURSOS_NUCRYPTO 
WHERE STATUS = '3' AND PERIOD = '12:00'

SELECT * 
FROM RPA.RPA_CTRL_ALERTA_RECURSOS_NUCRYPTO 
WHERE TO_DATE(DT_UPDATE) = TO_DATE(SYSDATE)
ORDER BY ID DESC

SELECT * FROM RPA.RPA_CTRL_ALERTA_RECURSOS_NUCRYPTO  
WHERE STATUS = '3' 
	AND PERIOD = '18:30'
	AND TO_DATE(DT_INSERT) = TO_DATE(SYSDATE)
